### ISSUE TITLE
Issue while running `go run convert_plugin.go` 

### ISSUE THREAD

**Issue by alichherawalla** [web-ridge/gqlgen-sqlboiler#3]
Thanks for this amazing library!

Currently when executing `go run convert_plugin.go` I'm getting the following error

panic: recursive or concurrent call to RenderToFile detected 

my gqlgen.yml looks like this 

```
schema:
  - schema.graphql
exec:
  filename: graphql/generated.go
  package: graphql
model:
  filename: graphql/models/generated_models.go
  package: gqlmodels
resolver:
  filename: graphql/resolver.go
  type: Resolver
``` 

any idea why this would be an issue?

**Comment by RichardLindhout** [comment]
The directories are a little bit hardcoded a.t.m. I will change that in next release. This is recommended.
Because the library thinks the sqlboiler models live in models/


gqlgen.yml
```
schema:
  - ../schema.graphql
exec:
  filename: graphql_models/generated.go
  package: graphql_models
model:
  filename: graphql_models/generated_models.go
  package: graphql_models
resolver:
  filename: resolver.go
  type: Resolver
```
